CREATE TABLE order_details (
    id INT PRIMARY KEY AUTO_INCREMENT,
    orders_id INT,
    products_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    deleted_at DATETIME,
    CONSTRAINT FK_Order FOREIGN KEY(orders_id)
    REFERENCES orders(id),
    CONSTRAINT FK_Product FOREIGN KEY(products_id)
    REFERENCES products(id)
) ENGINE=InnoDB;
